### Get web
GET http://localhost:8080

### Register user
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "test@gmail.com",
  "password": "password"
}

### Login user
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "test@gmail.com",
  "password": "password"
}